<a href="https://colab.research.google.com/github/FaezehNazemi/programming_with_python/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [10]:
import numpy as np
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(0,10, 3)

array([ 0.,  5., 10.])

import pandas as pd

In [2]:
import pandas as pd

In [10]:
my_index= ['USA','CANADA', 'Iran']
my_data=[1997,2001,2011]
my_ser= pd.Series(data=my_data, index=my_index)
my_ser['Iran']

2011

In [19]:
ages= {'sam':10, 'Ali':20, 'hamid':10}
my_age= pd.Series(ages)
my_age /2

sam       5.0
Ali      10.0
hamid     5.0
dtype: float64

In [15]:
import numpy as np
np.array([1,2]) * 2

array([2, 4])

In [24]:
import numpy as np
import pandas as pd
np.random.seed(101)
my_data=np.random.randint(0,101, (4,3))
my_data

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [25]:
my_index=['Japan','Iran','China','Dubai']
mycolumn= ['mar','jan','aug']
df= pd.DataFrame(my_data, my_index, mycolumn)
df

mar  jan  aug
Japan   95   11   81
Iran    70   63   87
China   75    9   77
Dubai   40    4   63